title: Tedap's CV and Blog
baseurl: ""
url: "https://tedap.github.io"
theme: minima
description: "My CV and personal blog"
sass:
  style: compressed
minima:
  skin: auto
  social_links: []
  include_css:
    - /assets/css/style.css
